[package]
name = "ingle-proc-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
ingle-codegen = { path = "../ingle-codegen" }
syn = "1"
